## 端口
server:
  port: 8003

## 应用名称
spring:
  application:
    name: service-oos

aliyun:
    oss:
      file:
        endpoint: oss-cn-beijing.aliyuncs.com
        keyid: LTAI4G6BVX9TVgny6ite2EMH
        keysecret: nVBBkJE0Mer0glSpmzJzMtMAhh9FVX
        bucketname: edu-1229